# Use root/example as user/password credentials
version: "3.4"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/conf.d:/etc/mysql/conf.d
    networks:
      - private
    ports:
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    restart: always
    networks:
      - private
    ports:
      - 8080:8080

networks:
  private:
